version: 0.2

phases:
  install:
    commands:
      - echo 'Installing NGINX - echo apt-get install NGINX'
      - sudo apt-get update
      - sudo apt-get install nginx -y
  build:
    commands:
      - echo 'Build started on $(date)'
      - mkdir -p var/www/html
      - cp index.html var/www/html
  post_build:
    commands:
      - echo 'Configuring NGINX'
      - aws s3 sync var/ s3://aws-cicd-demo-java-app-artifacts/var
